### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by rayk** [sirctseb/realtime-data-model#34]
Just started looking at this library for a project and I am assuming the examples have not been updated, they appear to refer to the jsintro stuff instead of dart:js.....  

I  hope missing anything...

**Comment by sirctseb** [comment]
You're right, I haven't update the examples for a long time. The unit tests in https://github.com/sirctseb/realtime-data-model/tree/master/test are up to date and should serve as an example in the mean time.

**Comment by rayk** [comment]
Thanks.... I change to read the code last night and thinking I make it work for what I want to do.. 

Thanks again....
